###
POST http://localhost:8000/register
Content-Type: application/json
Accept: application/json

{
  "name": "divo prapandita",
  "username": "dvoi84",
  "email": "divo@example.com",
  "password": "12345678"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
  "identifier": "dvoi84",
  "password": "12345678"
}

> {%
    client.global.set("token", response.body.token);
%}

### Login admin user
POST http://20.239.251.132:80/login
Content-Type: application/json

{
  "identifier": "superadmin",
  "password": "perpus"
}
> {%
    client.global.set("token", response.body.token)
 %}

### Get User
GET http://localhost:8000/me
Authorization: Bearer {{token}}

> {% 
    client.global.set("user_id", response.body.id);
%}

### Upload Real Ebook
POST http://localhost:8000/book/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="forester-commodore-hornblower.epub"
Content-Type: application/epub+zip

< ./forester-commodore-hornblower.epub
--WebAppBoundary--

### Delete a book
DELETE http://localhost:8000/book/commodore-hornblower
Authorization: Bearer {{token}}

### GET all books
GET http://localhost:8000/books

### Get detail book
GET http://localhost:8000/book/commodore-hornblower

> {% 
    client.global.set("book_id", response.body.book.id);
%}

### Get cover book
GET http://localhost:8000/book/commodore-hornblower/cover


### Borrow a book
POST http://localhost:8000/loans/borrow
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "book_id": "{{book_id}}",
    "user_id": "{{user_id}}",    "due_date": "2026-03-04"
}

### Check loan history
GET http://localhost:8000/loans/history
Authorization: Bearer {{token}}
Accept: application/json

### Return book
POST http://localhost:8000/loans/return/243a8a72-99e3-40ed-8b79-9db909492d7e
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json