POST http://localhost:8000/product/create
Content-Type: application/json


{
  "sku": "12332344",
  "name": "Garam ruqyah",
  "description": "Garam yang membuat rejeki lancar",
  "price": 12000,
  "quantity": 10
}

###
GET http://localhost:8000/product
Accept: application/json

###
POST http://localhost:8000/register
Content-Type: application/json

{
  "name": "divo prapandita",
  "username": "dvoi84",
  "email": "divo@example.com",
  "password": "12345678"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
  "identifier": "dvoi84",
  "password": "12345678"
}