server {
    listen 80;
    server_name _;

    # 1. Mengurus pengiriman gambar cover buku agar sangat cepat
    location /storage/ {
        alias /app/storage/;
        expires 30d;
    }

    # 2. Meneruskan sisa trafik API ke aplikasi Rust Axum
    location / {
        proxy_pass http://api_rust:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}