
use std::{env, fs, fs::File};
use std::io::Write;
use std::path::Path;
use std::process::Command;

fn main() {
    let _ = dotenv::dotenv().ok();

    // Ambil URL dengan aman menggunakan match, BUKAN unwrap/expect
    let db_url = match std::env::var("DATABASE_URL") {
        Ok(url) => url,
        Err(_) => {
            // Jika masuk ke sini (seperti saat di Vercel), script langsung berhenti DENGAN SUKSES
            println!("cargo:warning=DATABASE_URL tidak terdeteksi. Melewati generate entity.");
            return; 
        }
    };
    let out_dir = Path::new("src/generated");

    if out_dir.exists() {
        fs::remove_dir_all(out_dir).expect("Gagal hapus folder generated");
    }

    let status = Command::new("sea-orm-cli")
        .args(&[
            "generate", "entity",
            "--database-url", &db_url,
            "--output-dir", &out_dir.display().to_string(),
            "--with-serde", "both",
            "--impl-active-model-behavior=false"
        ])
        .status()
        .expect("sea-orm-cli failed to start");

    if !status.success() {
        panic!("Gagal generate entity");
    } else {
        generate_scaffold_files();
        // generate_generated_mod_rs();
        generate_mod_rs();
    }
    // Create generated/mod.rs by concatenating all generated .rs filenames
    // let mut mod_rs = String::new();
    // for entry in fs::read_dir(out_dir).unwrap() {
    //     let path = entry.unwrap().path();
    //     if path.extension().map_or(false, |ext| ext == "rs") {
    //         if let Some(stem) = path.file_stem() {
    //             mod_rs += &format!("pub mod {}\n", stem.to_string_lossy());
    //         }
    //     }
    // }
    //
    // fs::write(&gen_path, mod_rs).expect("Could not write mod.rs in OUT_DIR");
    //
    // Tell cargo to rerun if these files change
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=generated");
}

/// Generate a file from generated sea-orm
fn generate_scaffold_files() {
    let generated_dir = Path::new("src/generated");
    let custom_src_dir = Path::new("src");

    for entry in fs::read_dir(generated_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().map(|e| e == "rs").unwrap_or(false) {
            // let file_stem = path.file_stem().unwrap().to_string_lossy().to_string();
            // let custom_file_path = custom_src_dir.join(format!("{file_stem}.rs"));

            if path.extension().map(|e| e == "rs").unwrap_or(false) {
                let file_stem = path.file_stem().unwrap().to_string_lossy().to_string();
                if file_stem == "lib" || file_stem == "prelude" || file_stem == "mod" {
                    continue; // skip file umum
                }

                let custom_file_path = custom_src_dir.join(format!("{file_stem}.rs"));
                if !custom_file_path.exists() {
                    let mut file = File::create(&custom_file_path).unwrap();

                    writeln!(file, "use sea_orm::entity::prelude::*;").unwrap();
                    writeln!(file, "use crate::generated::{} as generated;\n", file_stem).unwrap();
                    writeln!(file, "pub use generated::*;\n").unwrap();
                    writeln!(file, "impl ActiveModelBehavior for generated::ActiveModel {{}}\n").unwrap();

                    println!("Scaffold created: {}", custom_file_path.display());
                }
            }
        }
    }
}

fn generate_mod_rs() {
    let custom_src_dir = Path::new("src");
    let mod_rs_path = custom_src_dir.join("mod.rs");

    let mut mod_file = File::create(&mod_rs_path).unwrap();

    writeln!(
        mod_file,
        "// Auto-generated mod.rs, will overwrite every build\n\
         // Do NOT put custom code here.\n"
    )
        .unwrap();

    for entry in fs::read_dir(custom_src_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().map(|e| e == "rs").unwrap_or(false) {
            let file_stem = path.file_stem().unwrap().to_string_lossy();
            if file_stem != "mod" {
                writeln!(mod_file, "pub mod {};", file_stem).unwrap();
            }
        }
    }

    println!("Updated mod.rs: {}", mod_rs_path.display());
}
fn generate_generated_mod_rs() {
    let generated_dir = Path::new("generated");
    let mod_rs_path = generated_dir.join("mod.rs");

    let mut mod_file = File::create(&mod_rs_path).expect("Gagal membuat generated/mod.rs");

    writeln!(
        mod_file,
        "// Auto-generated by build.rs for SeaORM entity modules\n\
         // Do NOT manually edit this file\n"
    ).unwrap();

    for entry in fs::read_dir(generated_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();

        if path.extension().map(|ext| ext == "rs").unwrap_or(false) {
            let file_stem = path.file_stem().unwrap().to_string_lossy();
            if file_stem != "mod" {
                writeln!(mod_file, "pub mod {};", file_stem).unwrap();
            }
        }
    }

    println!("Updated generated/mod.rs: {}", mod_rs_path.display());
}
